services:
  localnet:
    ports:
      - 8545:8545
    build:
      context: ./localnet
      dockerfile: dockerfile.localnet
  backend:
    ports:
      - 5000:5000
    build:
      context: ./backend
      dockerfile: dockerfile.backend
    depends_on:
      - localnet
    volumes:
      - ./backend:/srcs
      - /srcs/node_modules

