FROM python:latest

WORKDIR /srcs

# Copy only requirements.txt first
COPY requirements.txt /srcs/

RUN pip install -r requirements.txt

# For Python, we typically use python instead of npm
CMD ["python", "app.py"]